### ISSUE TITLE
DCAT-US writer: conditional fields

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdTranslator#268]
# Issue

Add support for [DCAT-US schema](https://resources.data.gov/resources/dcat-us) conditional fields. 

## For information on the DCAT-US schema see:

  - https://resources.data.gov/schemas/dcat-us/v1.1/schema/dataset.json
  - https://resources.data.gov/resources/dcat-us
  - https://github.com/adiwg/mdTranslator/blob/feature/dcat-us-writer/notes.md

## Conditional fields:

  - [x] license (see PR #274)
  - [x] rights (see PR #274)
  - [x] spatial (see PR #274)
  - [x] temporal (see PR #274)
  - [x] distribution (see PR #274)
  
# Proposed mapping of mdJSON to DCAT-US conditional fields.

## [license](https://resources.data.gov/resources/dcat-us/#license)
| Field Name | DCAT Name | Condition | mdJson Source |
| --- | --- | --- | --- |
| License | dcat:license | [*add resourceInfo.constraint.reference to mdEditor*] <br> if exists resourceInfo.constraint.reference[0] | resourceInfo.constraint.reference[0] <br> |
| | | else | https://creativecommons.org/publicdomain/zero/1.0/ <br> [*allows author to identify a license to use, or default to CC0 if none provided, CC0 would cover international usage as opposed to publicdomain*] <br> [*others: http://www.usa.gov/publicdomain/label/1.0/, http://opendatacommons.org/licenses/pddl/1.0*] |

## [rights](https://resources.data.gov/resources/dcat-us/#rights)

| Field Name | DCAT Name | Condition | mdJson Source |
| --- | --- | --- | --- |
| Rights | dcat:rights | if constraint.accessLevel in {"restricted public", "non-public"} | resourceInfo.constraint.releasibility.statement + " " + each constraint.releasibility.dessiminationConstraint[0, n] |

## [spatial](https://resources.data.gov/resources/dcat-us/#spatial)

| Field Name | DCAT Name | Condition | mdJson Source |
| --- | --- | --- | --- |
| Spatial | dcat:spatial | if exists resourceInfo.extents[0].geographicExtents[0].boundingBox | boundingBox.eastLongitude + "," + boundingBox.southLatitude + "," + boundingBox.westLongitude + "," + boundingBox.northLatitude [*decimal degrees*] |
| | | else | if exists resourceInfo.extents[0].geographicExtents[0].geographicElement[0].type = "point" then <br> geographicElement[0].coordinate[1] + "," + geographicElement[0].coordinate[0] [*lat, long decimal degrees*] |

## [temporal](https://resources.data.gov/resources/dcat-us/#temporal)

| Field Name | DCAT Name | Condition | mdJson Source |
| --- | --- | --- | --- |
| Temporal | dcat:temporal | if exists resourceInfo.extent[0].temporalExtent[0] then <br> if exists tempororalExtent[0].timePeriod.startDate and exists temporaralExtent[0].timePeriod.endDate | timePeriod[0].startDate + "/" + timePeriod.endDate |
| | | if exists  tempororalExtent[0].timePeriod.startDate and not exists temporaralExtent[0].timePeriod.endDate | tempororalExtent[0].timePeriod.startDate |
| | | if not exists temporalExtent[0].timePeriod.startDate and exists temporaralExtent[0].timePeriod.endDate | tempororalExtent[0].timePeriod.endDate <br> [*may need revisiting relative to decision on date only formatting*] |

## [distribution](https://resources.data.gov/resources/dcat-us/#distribution)

[*Moved to new issue*](https://github.com/adiwg/mdTranslator/issues/275)

**Comment by dwalt** [comment]
Temporal is incorrectly mapped for mdJSON, though correct for ISO. At this point, I believe we are only considering mdJSON-DCAT. Should be resourceInfo.timePeriod{ }.

**Comment by dwalt** [comment]
Rights logic won't work. There is no "accessLevel" in mdJSON. Following the logic that Hilmar suggested in [DCAT.md](https://github.com/adiwg/mdTranslator/blob/feature/DCAT-US-v1/DCAT-US.md) of using MD_ClassificationCode, possibly utilizing codes "unclassified" and "restricted". However, I don't see a suitable code to imply "non-public". We may consider extending the codelist to explicitly identify these codes, or just add non-public to the list. Modified logic would like this:

if constraint[0] exists, and for any constraint[ ] 
  if security.classification = "unclassified" or "public" then rights = "Public"
  else if security.classification = "restricted" or "restrictedPublic" then rights = "Restricted Public"
  else if security.classification = "nonPublic" = then rights = "Non Public"
